# This is a basic workflow to help you get started with Actions

name: GitHub for IT Pro CI/CD Pipeline

env:
  OUTPUT_PATH: ${{ github.workspace}}

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Deploy VM in Azure"
  DeployVM:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo
        uses: actions/checkout@v1

      # Runs a single command using the runners shell
      - name: look for ps1 file
        run: |
          ls '${{} env.OUTPUT_PATH }}\IaC\AzCLI'

      # Runs a set of commands using the runners shell
      - name: provision virtual machine in azure
        env:
          RESOURCE_GROUP: DisaTesting
          RESOURCE_GROUP_REGION: EastUS
          SERVER_NAME: githubactions
          ADMIN_LOGIN: david
        run: >
          powershell -command "& '${{ env.OUTPUT_PATH }}\IaC\AzCLI\deployvnets.ps1'"
          -servicePrincipal ${{ secrets.SERVICE_PRINCIPAL_APPID }}
          -servicePrincipalSecret ${{ secrets.SERVICE_PRINCIPAL_SECRET }}
          -servicePrincipalTenantId ${{ secrets.SERVICE_PRINCIPAL_TENANTID }}
          -azureSubscriptionName ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          -resourceGroupName %RESOURCE_GROUP%
          -resourceGroupNameRegion %RESOURCE_GROUP_REGION%
          -serverName %SERVER_NAME%
          -adminLogin %ADMIN_LOGIN%
          -adminPassword ${{ secrets.ADMIN_PASSWORD }}
